# Autogenerated wrapper script for OpenCL_Headers_jll for x86_64-linux-gnu
export cl_h

JLLWrappers.@generate_wrapper_header("OpenCL_Headers")
JLLWrappers.@declare_file_product(cl_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        cl_h,
        "include/CL/cl.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
